language: python

python:
  - 2.6
  - 2.7
# - 3.3

services: postgresql

env:
  - DJANGO=1.4.2

before_install:
  - export DJANGO_SETTINGS_MODULE=ponyforum.settings
  - export PYTHONPATH=$HOME/builds/ndarville/pony-forum
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
# - pip install pip-tools --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py syncdb --noinput
  - python manage.py schemamigration forum --initial
  - python manage.py migrate forum --fake

script:
  - python _postinstall/mkadmin.py
  - python _postinstall/definesite.py
  - python _postinstall/mkplaceholders.py
  - python manage.py test

after_success:
- "pep8 --statistics --first --format=pylint --exclude=venv,virtualenv,migrations"

notifications:
  email:
    on_success: change
    on_failure: always

# matrix:
#   allow_failures:
#     - python: 3.3
