language: python

python:
  - 2.6
  - 2.7
# - 3.3

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="ponyforum.settings"
  - PYTHONPATH="/home/travis/build/ndarville/pony-forum"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
# - pip install django==$DJANGO --quiet
  - pip install coveralls radon
# - pip install pip-tools --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py syncdb --noinput
  - python manage.py schemamigration forum --initial
  - python manage.py migrate forum --fake

script:
  - python _postinstall/mkadmin.py
  - python _postinstall/definesite.py
  - python _postinstall/mkplaceholders.py
  - python manage.py test

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls
- echo Code complexity scores:; radon cc --min B ../pony-forum

notifications:
  email:
    on_success: change
    on_failure: always

# matrix:
#   allow_failures:
#     - python: 3.3
